.TH CLEARINPUTBUFFER 3 "August 2024" "Tic-Tac-Toe Library" "Library Functions Manual"
.SH NAME
clearInputBuffer \- clear the input buffer

.SH SYNOPSIS
.nf
.B #include "Game.h"
.BI "void clearInputBuffer(void);"
.fi

.SH DESCRIPTION
The
.B clearInputBuffer
function clears any remaining characters from the input buffer, typically after reading user input. This prevents erroneous input in subsequent operations.

.SH PARAMETERS
None.

.SH RETURN VALUE
This function does not return a value.

.SH SEE ALSO
.BR playerAction (3)

.SH AUTHOR
Your Name <veronauan@gmail.com>
