.TH CLEARSCEEN 3 "August 2024" "Tic-Tac-Toe Library" "Library Functions Manual"
.SH NAME
clearScreen \- clear the terminal screen

.SH SYNOPSIS
.nf
.B #include "Board.h"
.BI "void clearScreen(void);"
.fi

.SH DESCRIPTION
The
.B clearScreen
function clears the terminal screen. It uses the appropriate command for the operating system: `cls` for Windows and `clear` for Unix-like systems.

.SH AUTHOR
metavenoma <veronauan@gmail.com>
